# Generated by Django 4.1 on 2022-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='thumbnail',
            field=models.ImageField(default='icon/sugar.png', upload_to='', verbose_name='サムネイル'),
        ),
    ]
