# Generated by Django 4.1 on 2022-08-16 05:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('diary', '日記'), ('python', 'python')], default=datetime.datetime(2022, 8, 16, 5, 37, 13, 23022, tzinfo=datetime.timezone.utc), max_length=40, verbose_name='カテゴリー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=models.TextField(verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='post_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
