# Generated by Django 4.1 on 2022-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル'),
        ),
    ]
