# Generated by Django 4.1 on 2022-08-16 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_category_alter_blogmodel_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='tag',
            field=models.CharField(choices=[('diary', '日記'), ('python', 'パイソン')], default=datetime.datetime(2022, 8, 16, 5, 39, 32, 995420, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('diary', '日記'), ('python', 'パイソン')], max_length=40, verbose_name='カテゴリー'),
        ),
    ]
