# Generated by Django 4.1 on 2022-09-21 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmodel_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無さん', max_length=30, verbose_name='名前')),
                ('text', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメント投稿日')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='対象記事')),
            ],
        ),
    ]
