# Generated by Django 4.1 on 2022-09-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_created_at_alter_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='relation_posts',
            field=models.ManyToManyField(blank=True, to='blog.blogmodel', verbose_name='関連記事'),
        ),
    ]
